org: Data-Epic
app: sol-sight-serverless
service: sol-sight-serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  iamRoleStatements:
  - Effect: Allow
    Action:
      - firehose:DeleteDeliveryStream
      - firehose:PutRecord
      - firehose:PutRecordBatch
      - firehose:UpdateDestination
    Resource: '*'

functions:
  hello:
    handler: datalake/api.hello

resources: ${file(resources/serverless.yml)}