# org: Data-Epic
# app: sol-sight-serverless
service: sol-sight-serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions: ${file(datalake/api.yml)}

resources: ${file(resources/serverless.yml)}

plugins:
  - serverless-localstack
  - serverless-iam-roles-per-function